[build]
  publish = "dist"
  functions = "functions"

[[plugins]]
  package = "@netlify/functions"

[functions]
  directory = "functions"

[[plugins]]
package = "@netlify/plugin-inline-functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
